### PR TITLE
Modify Makefile for packaging, add manpage

### PR DESCRIPTION
**Pull request by The-King-of-Toasters**
I came across your post on [lobste.rs](https://lobste.rs/s/px1nxk/modern_more_featured_echo) and was interested in helping out. I've modified the Makefile to use the `all`, `install` and `clean` targets, as well as adding support for `DESTDIR` and the implicit `CXX` and `CPPFLAGS` vars.
I also added a manpage by looking at the help text.

### CODE REVIEW

**Comment by Unlimiter** [comment]
Can you change the author name in the manpage from "Hesham Labidi" to "Unlimiter" before I merge your pull request?

**Comment by Unlimiter** [comment]
@The-King-of-Toasters Btw, I made a new release with updated usage text, you should update the manpage according to the usage text.

**Comment by The-King-of-Toasters** [comment]
Sure. It's a bit late for me right now, but I can do it soon.

**Comment by Unlimiter** [comment]
@The-King-of-Toasters I'll actually do it.

**Comment by The-King-of-Toasters** [comment]
Aaand I boned the commit log. Gimmie a minute.

**Comment by The-King-of-Toasters** [comment]
Right, all good again. I changed the author name aswell. Before you merge the changes, I'd like to flesh out the color/attribute section. I've worked with similar programs that do this and I've referenced the SGR section of ECMA-48 to do this. I'll just copy the relevant sections from my prior work into here. But I'll get to it tomorrow. Thanks for your understanding :).

**Pull request merged**
